title: Родословная и история села Изосимово
description: Книга об исследовании родословной, истории села Изосимово, однодворцах Тамбовского края, а также о жизни и карьере Александра Христофоровича Бенкендорфа.
lang: ru
theme: jekyll-theme-cayman
